config/routes.rb
Rails.application.routes.draw do
  resources :moods
  
  root 'moods#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/journal.rb
 class Journal < ApplicationRecord  belongs_to :mood, optional: trueend

app/models/mood.rb
class Mood < ApplicationRecord
    has_many :mood_triggers, dependent: :destroy
    has_many :triggers, through: :mood_triggers
  end

app/models/trigger.rb
class Trigger < ApplicationRecord
    has_many :mood_triggers, dependent: :destroy
    has_many :moods, through: :mood_triggers
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
    def new
      @mood = Mood.new
    end
    
    def create
      @mood = Mood.new(mood_params)
      if @mood.save
        redirect_to @mood
      else
        render 'new'
      end
    end
    
    def show
      @mood = Mood.find(params[:id])
      if @mood.nil? || @mood.date.nil? || @mood.mood.nil? || @mood.notes.nil?
        flash[:error] = "Sorry, something went wrong. Please try again later."
        redirect_to root_path
    end
    
    private
    
    def mood_params
      params.require(:mood).permit(:name, :description)
    end
  end
end
  

app/controllers/triggers_controller.rb
class TriggersController < ApplicationController
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/triggers_helper.rb
module TriggersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Moodtracker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/moods/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Responsive Ruby on Rails Form</title>

  <style>
    /* Import the Poppins font from Google Fonts */
    @import url('https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600&display=swap');

    body {
      background-color: #f5f5f5;
      margin-bottom: 30px;
      text-align: center;
      font-size: 16px;
      font-family: 'Poppins', sans-serif;
      line-height: 1.5;
    }

    .form-title {
      text-align: center;
      margin-top: 50px;
      margin-bottom: 30px;
      font-size: 36px;
      color: #4d4d4d;
    }

    .form-container {
      max-width: 400px;
      width: 100%;
      margin: 0 auto;
      border-radius: 10px;
      background-color: white;
      padding: 30px;
      box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
    }

    .form-row {
      margin-bottom: 20px;
    }

    .form-label {
      display: block;
      margin-bottom: 10px;
      font-size: 18px;
      font-weight: 600;
      color: #4d4d4d;
    }

    .form-input {
      font-family: 'Poppins', sans-serif;
      font-size: 16px;
      color: #333;
      border: none;
      background: #fff;
      padding: 0.5rem 1rem;
      border-radius: 0.25rem;
      box-shadow: 0 0 0 1px #ccc;
      width: 100%;
      resize: none;
      box-sizing: border-box;
    }

    select {
      font-family: 'Poppins', sans-serif;
      font-size: 16px;
      color: #333;
      border: none;
      background: #fff;
      padding: 0.5rem 1rem;
      border-radius: 0.25rem;
      box-shadow: 0 0 0 1px #ccc;
      width: 100%;
      box-sizing: border-box;
    }

    select:focus {
      outline: none;
      box-shadow: 0 0 0 2px #2756af;
    }

    .form-submit {
      display: flex;
      justify-content: center;
      align-items: center;
    }

    .form-submit-button {
      background-color: #37B34A;
      color: white;
      padding: 12px 20px;
      border: none;
      border-radius: 5px;
      cursor: pointer;
      transition: background-color 0.2s ease-in-out;
      width: 100%;
      box-sizing: border-box;
    }

    .form-submit-button:hover {
      background-color: #52C87C;
    }

    .show-link-container {
     
    display: flex;
    justify-content: center;
    align-items: center;
  }

  .show-link {
    background-color: #4d4d4d;
    color: white;
    display: inline-block;
    padding: 10px 20px;
    text-align: center;
    text-decoration: none;
    border-radius: 5px;
    font-size: 16px;
    transition: background-color 0.2s ease-in-out;
  }

  .show-link:hover {
    background-color: #5d5d5d;
  }

  .alert {
    padding: 8px;
    background-color: #f44336;
    color: white;
    border-radius: 5px;
    margin-bottom: 30px;
    text-align: center;
    font-size: 16px;
  }

  @media screen and (max-width: 768px) {
    .form-title {
      font-size: 28px;
    }

    .form-container {
      padding: 20px;
    }
  }
</style>
</head>
<body>
<h1 class="form-title">Create a new mood</h1>

<% if flash[:error] %>
  <div class="alert alert-danger"><%= flash[:error] %></div>
<% end %>

<div class="form-container">
  <%= form_with(model: @mood, url: moods_path) do |form| %>
    <div class="form-row">
      <%= form.label :date, class: 'form-label' %>
      <%= form.datetime_local_field :date, class: 'form-input' %>
    </div>

    <div class="form-row">
    <%= form.label :mood, class: 'form-label' %>
    <%= form.select :mood, [
      ["😀 Happy", "Happy"],
      ["😭 Sad", "Sad"],
      ["😠 Angry", "Angry"],
      ["😍 Excited", "Excited"],
      ["🥰 Loved", "Loved"],
      ["🤔 Thoughtful", "Thoughtful"]
    ], { }, class: 'form-input' %>
  </div>
  

    <div class="form-row">
      <%= form.label :notes, class: 'form-label' %>
      <%= form.text_area :notes, class: 'form-input', id: 'mood_notes', name: 'mood_notes', placeholder: 'Additional notes' %>
    </div>

    <div class="form-row form-submit">
      <%= form.submit 'Create Mood', class: 'form-submit-button' %>
    </div>
  <% end %>

  <div class="form-row show-link-container">
    <%= link_to 'Show existing moods', moods_path, class: 'show-link' %>
  </div>
</div>

<script>
  const textArea = document.getElementById('mood_notes');

  textArea.addEventListener('input', updateTextAreaHeight);

  function updateTextAreaHeight() {
    textArea.style.height = 'auto';
    textArea.style.height = textArea.scrollHeight + 'px';
  }
</script>
</body>
</html>

app/views/moods/show.html.erb
<h1><%= @mood.name %></h1>

<p><%= @mood.description %></p>

<p>Created at: <%= @mood.created_at %></p>